#include "Keyboard.h"

namespace rvl {
	bool Keyboard::IsKeyPressed(int32 keycode) {
		return sf::Keyboard::isKeyPressed(sf::Keyboard::Key(keycode));
	}

	void Keyboard::DoBind(lua_State * Lua) {
		luabridge::getGlobalNamespace(Lua)
			.beginNamespace("rvl")
				.beginClass<Keyboard>("Keyboard")
					.addConstructor<void(*)(void)>()
					.addStaticFunction("IsKeyPressed", &rvl::Keyboard::IsKeyPressed)
					.addData("A", &rvl::Keyboard::A, false)
					.addData("B", &rvl::Keyboard::B, false)
					.addData("C", &rvl::Keyboard::C, false)
					.addData("D", &rvl::Keyboard::D, false)
					.addData("E", &rvl::Keyboard::E, false)
					.addData("F", &rvl::Keyboard::F, false)
					.addData("G", &rvl::Keyboard::G, false)
					.addData("H", &rvl::Keyboard::H, false)
					.addData("I", &rvl::Keyboard::I, false)
					.addData("J", &rvl::Keyboard::J, false)
					.addData("K", &rvl::Keyboard::K, false)
					.addData("L", &rvl::Keyboard::L, false)
					.addData("M", &rvl::Keyboard::M, false)
					.addData("N", &rvl::Keyboard::N, false)
					.addData("O", &rvl::Keyboard::O, false)
					.addData("P", &rvl::Keyboard::P, false)
					.addData("Q", &rvl::Keyboard::Q, false)
					.addData("R", &rvl::Keyboard::R, false)
					.addData("S", &rvl::Keyboard::S, false)
					.addData("T", &rvl::Keyboard::T, false)
					.addData("U", &rvl::Keyboard::U, false)
					.addData("V", &rvl::Keyboard::V, false)
					.addData("W", &rvl::Keyboard::W, false)
					.addData("X", &rvl::Keyboard::X, false)
					.addData("Y", &rvl::Keyboard::Y, false)
					.addData("Z", &rvl::Keyboard::Z, false)
					.addData("Num0", &rvl::Keyboard::Num0, false)
					.addData("Num1", &rvl::Keyboard::Num1, false)
					.addData("Num2", &rvl::Keyboard::Num2, false)
					.addData("Num3", &rvl::Keyboard::Num3, false)
					.addData("Num4", &rvl::Keyboard::Num4, false)
					.addData("Num5", &rvl::Keyboard::Num5, false)
					.addData("Num6", &rvl::Keyboard::Num6, false)
					.addData("Num7", &rvl::Keyboard::Num7, false)
					.addData("Num8", &rvl::Keyboard::Num8, false)
					.addData("Num9", &rvl::Keyboard::Num9, false)
					.addData("Escape", &rvl::Keyboard::Escape, false)
					.addData("LControl", &rvl::Keyboard::LControl, false)
					.addData("LShift", &rvl::Keyboard::LShift, false)
					.addData("LAlt", &rvl::Keyboard::LAlt, false)
					.addData("LSystem", &rvl::Keyboard::LSystem, false)
					.addData("RControl", &rvl::Keyboard::RControl, false)
					.addData("RShift", &rvl::Keyboard::RShift, false)
					.addData("RAlt", &rvl::Keyboard::RAlt, false)
					.addData("RSystem", &rvl::Keyboard::RSystem, false)
					.addData("RBracket", &rvl::Keyboard::RBracket, false)
					.addData("LBracket", &rvl::Keyboard::LBracket, false)
					.addData("Menu", &rvl::Keyboard::Menu, false)
					.addData("SemiColon", &rvl::Keyboard::SemiColon, false)
					.addData("Comma", &rvl::Keyboard::Comma, false)
					.addData("Period", &rvl::Keyboard::Period, false)
					.addData("Quote", &rvl::Keyboard::Quote, false)
					.addData("Slash", &rvl::Keyboard::Slash, false)
					.addData("BackSlash", &rvl::Keyboard::BackSlash, false)
					.addData("Tilde", &rvl::Keyboard::Tilde, false)
					.addData("Equal", &rvl::Keyboard::Equal, false)
					.addData("Dash", &rvl::Keyboard::Dash, false)
					.addData("Space", &rvl::Keyboard::Space, false)
					.addData("Return", &rvl::Keyboard::Return, false)
					.addData("BackSpace", &rvl::Keyboard::BackSpace, false)
					.addData("Tab", &rvl::Keyboard::Tab, false)
					.addData("PageUp", &rvl::Keyboard::PageUp, false)
					.addData("PageDown", &rvl::Keyboard::PageDown, false)
					.addData("End", &rvl::Keyboard::End, false)
					.addData("Home", &rvl::Keyboard::Home, false)
					.addData("Insert", &rvl::Keyboard::Insert, false)
					.addData("Delete", &rvl::Keyboard::Delete, false)
					.addData("Add", &rvl::Keyboard::Add, false)
					.addData("Subtract", &rvl::Keyboard::Subtract, false)
					.addData("Multiply", &rvl::Keyboard::Multiply, false)
					.addData("Divide", &rvl::Keyboard::Divide, false)
					.addData("Left", &rvl::Keyboard::Left, false)
					.addData("Right", &rvl::Keyboard::Right, false)
					.addData("Up", &rvl::Keyboard::Up, false)
					.addData("Down", &rvl::Keyboard::Down, false)
					.addData("Numpad0", &rvl::Keyboard::Numpad0, false)
					.addData("Numpad1", &rvl::Keyboard::Numpad1, false)
					.addData("Numpad2", &rvl::Keyboard::Numpad2, false)
					.addData("Numpad3", &rvl::Keyboard::Numpad3, false)
					.addData("Numpad4", &rvl::Keyboard::Numpad4, false)
					.addData("Numpad5", &rvl::Keyboard::Numpad5, false)
					.addData("Numpad6", &rvl::Keyboard::Numpad6, false)
					.addData("Numpad7", &rvl::Keyboard::Numpad7, false)
					.addData("Numpad8", &rvl::Keyboard::Numpad8, false)
					.addData("Numpad9", &rvl::Keyboard::Numpad9, false)
					.addData("F1", &rvl::Keyboard::F1, false)
					.addData("F2", &rvl::Keyboard::F2, false)
					.addData("F3", &rvl::Keyboard::F3, false)
					.addData("F4", &rvl::Keyboard::F4, false)
					.addData("F5", &rvl::Keyboard::F5, false)
					.addData("F6", &rvl::Keyboard::F6, false)
					.addData("F7", &rvl::Keyboard::F7, false)
					.addData("F8", &rvl::Keyboard::F8, false)
					.addData("F9", &rvl::Keyboard::F9, false)
					.addData("F10", &rvl::Keyboard::F10, false)
					.addData("F11", &rvl::Keyboard::F11, false)
					.addData("F12", &rvl::Keyboard::F12, false)
					.addData("F13", &rvl::Keyboard::F13, false)
					.addData("F14", &rvl::Keyboard::F14, false)
					.addData("F15", &rvl::Keyboard::F15, false)
				.endClass()
			.endNamespace();
	}

}
